# Generated by Django 6.0.1 on 2026-01-08 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CAFVEligibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='EVType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('postal_code', models.CharField(max_length=16)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ev_app.county')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ev_app.make')),
            ],
        ),
        migrations.AddField(
            model_name='county',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ev_app.state'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('vin_prefix', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('model_year', models.IntegerField()),
                ('electric_range', models.IntegerField()),
                ('legislative_district', models.IntegerField()),
                ('cafv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ev_app.cafveligibility')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ev_app.city')),
                ('ev_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ev_app.evtype')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ev_app.model')),
            ],
        ),
    ]
